server:
  port:
    8082

spring:
  application:
    name: API_GATEWAY


  cloud:
    gateway:
      routes:
       - id: product-service
         uri:
           http://localhost:8086/product/
         predicates:
         - Path=/product/**

       - id: product-details-service
         uri:
           http://localhost:8083/productdetails/
         predicates:
         - Path=/productdetails/**

       - id: cart-service
         uri:
           http://localhost:8081/cart/
         predicates:
           - Path=/cart/**

       - id: inventory-service
         uri:
           http://localhost:8082/inventory/
         predicates:
           - Path=/inventory/**

       - id: cart-service
         uri:
           http://localhost:8081/cart/
         predicates:
           - Path=/cart/**
