server:
  port:
    8082

spring:
  application:
    name: API_GATEWAY


  cloud:
    gateway:
      routes:
       - id: customer-management-service
         uri:
           http://localhost:8080/api/v1/customer/
         predicates:
         - Path=/api/v1/customer/**

       - id: ACCOUNT-MANAGEMENT-SERVICE
         uri:
           http://localhost:8081/api/v1/account/
         predicates:
         - Path=/api/v1/account/**
